site_name: Scarf Documentation
theme: readthedocs
nav:
- Introduction: 'index.md'
- Package analytics SDKs: 'package-analytics.md'
- Package manager (maintainers): 'distribute-with-scarf.md'
- Package manager (end-user): 'end-user.md'
